name: Crystal CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal

    steps:
      - name: Checkout source
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
  
      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@8c84e3955cc1717588b2207204728f7d805c6690 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install dependencies
        run: shards install
  
      - name: Run tests
        run: crystal spec
